wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
